#!/bin/sh

SERVERIP=$1

RE="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"
adb devices | grep $RE | sed -e "s/\($RE\):.*/\1/g" | while read line; do  adb disconnect "${line}:5555" ; done

if [ -z "$SERVERIP" ]
then
adb connect 10.68.12.23
#adb connect 10.68.12.248
else
#adb connect $SERVERIP:5555 
adb connect $SERVERIP 
fi
adb devices

