#!/bin/sh
usage()
{
	echo "Delete the last N bytes of the file" >&2
	echo "usage: $(basename $0) [length_of_data_to_delete] [filename]" >&2
	exit 1
}

if [ $# -ne 2 ];then
    usage
fi
LENGTH=$1
FILESIZE=$(stat --format=%s $2)
FILESIZE=$(expr ${FILESIZE} - ${LENGTH})

truncate -s ${FILESIZE} $2 

