#!/bin/sh

usage()
{
        echo "usage: $(basename $0) [addr] [ path of library or binary]" >&2
        echo "  $(basename $0) [addr] [ path of library or binary]" >&2
        echo "  $(basename $0) -a [addr] [ path of library or binary]" >&2
        echo "Before running the command. please export the variable" >&2
        echo "export DECOMPILE_ANDROID_TOP=YOURPATH" >&2
        echo "export DECOMPILE_ANDROID_TARGET_PRODUCT=YOURTARGET" >&2
        echo "FOR example:" >&2
        echo "export DECOMPILE_ANDROID_TOP=/mnt/fileroot/gaokejun/kk-amlogic" >&2
        echo "export DECOMPILE_ANDROID_TOP=/mnt/fileroot/gaokejun/l-amlogic" >&2
        echo "export DECOMPILE_ANDROID_TOP=/mnt/fileroot/gaokejun/m-amlogic" >&2
        echo "export DECOMPILE_ANDROID_TOP=/mnt/fileroot/gaokejun/n-amlogic" >&2
        echo "export DECOMPILE_ANDROID_TARGET_PRODUCT=p201" >&2
        echo "export DECOMPILE_ANDROID_TARGET_PRODUCT=p212" >&2

	 	exit 1
}

if [ $# -lt 2 ]; then
  usage
fi

SHOULD_ADJUST=0

if [ $# -eq 2 ]; then
	ADDR=$1
	FILEPATH=$2
elif [ $# -eq 3 -a "-a" = $1 ]; then
  SHOULD_ADJUST=1
	ADDR=$2
	FILEPATH=$3
else
  usage
fi



ADDR=$( echo $ADDR | tr  '[:lower:]' '[:upper:]')
FILEPATH=$DECOMPILE_ANDROID_TOP/out/target/product/$DECOMPILE_ANDROID_TARGET_PRODUCT/symbols/$FILEPATH

if [ $SHOULD_ADJUST -eq 1 ]; then  
ADJUST=$(readelf -l $FILEPATH | \
		grep LOAD | \
		head -n 1 | \
		awk '{print $3}' | \
		cut -b 3- | \
		tr  '[:lower:]' '[:upper:]' )

#echo ADJUST=$ADJUST

ADDR="obase=10; ibase=16; $ADDR"
ADJUST="obase=10; ibase=16; $ADJUST"
ADDR=$(echo $ADDR | bc)
ADJUST=$(echo $ADJUST | bc)
#echo ADDR=$ADDR
#echo ADJUST=$ADJUST

ADDR=$(echo $ADDR+$ADJUST | bc)
ADDR="obase=16; ibase=10; $ADDR"
ADDR=$(echo $ADDR | bc)
#echo $ADDR
fi  

echo DECOMPILE_ANDROID_TOP[$DECOMPILE_ANDROID_TOP]
echo DECOMPILE_ANDROID_TARGET_PRODUCT[$DECOMPILE_ANDROID_TARGET_PRODUCT]

addr2line -e $FILEPATH $ADDR

