sed -i '/System.out/d' $1
sed -i '/System.err/d' $1


sed -i '/NetlinkEvent/d' $1
sed -i '/PppoeStateTracker/d' $1
sed -i '/ConnectivityChangeNotifier/d' $1
sed -i '/ConnectionReceiver/d' $1
sed -i '/ConnectionMonitor/d' $1
sed -i '/AmlogicUtils/d' $1
sed -i '/SystemClock/d' $1
sed -i '/WelcomeActivity/d' $1
sed -i '/C1MainPageActivity/d' $1
sed -i '/AlarmManager/d' $1
sed -i '/libEGL/d' $1
sed -i '/OpenGLRenderer/d' $1
sed -i '/PowerManagerService/d' $1
sed -i '/InputMethodManagerService/d' $1
sed -i '/PlaySimpleControl/d' $1
sed -i '/ThrottleService/d' $1
sed -i '/PlayingStateHandler/d' $1
sed -i '/Choreographer/d' $1
sed -i '/WVMExtractorImpl/d' $1
sed -i '/PlayActivity/d' $1
sed -i '/SystemUtil/d' $1
sed -i '/BaseDAO/d' $1
sed -i '/hwcomposer/d' $1

sed -i '/AmlogicPlayer/d' $1
sed -i '/AmSuperPlayer/d' $1
sed -i '/amplayer/d' $1
sed -i '/DirectVolume/d' $1
sed -i '/MediaProvider/d' $1
sed -i '/sub_jni/d' $1
sed -i '/MediaCenter/d' $1
sed -i '/ALSA/d' $1

sed -i '/MediaScannerReceiver/d' $1
sed -i '/TabletStatusBar/d' $1
sed -i '/SystemUIService/d' $1
sed -i '/VoldConnector/d' $1
sed -i '/BackupManagerService/d' $1
sed -i '/ActivityThread/d' $1
sed -i '/amcodec/d' $1
sed -i '/MenuListAdapter/d' $1
sed -i '/ActivityManager/d' $1
sed -i '/PackageManager/d' $1
sed -i '/voltage/d' $1
sed -i '/ircode/d' $1
sed -i '/MountService/d' $1
sed -i '/StorageNotification/d' $1
sed -i '/audio/d' $1
sed -i '/Audio/d' $1
sed -i '/subtitle/d' $1
sed -i '/VideoView/d' $1
sed -i '/xiaoxizhe/d' $1
sed -i '/PinyinIME/d' $1
sed -i '/TerminalUtils/d' $1
sed -i '/LETV/d' $1
sed -i '/dalvikvm/d' $1
sed -i '/utp/d' $1
sed -i '/amffmpeg/d' $1
sed -i '/amadec/d' $1
sed -i '/InSubApi/d' $1
sed -i '/SurfaceFlinger/d' $1
sed -i '/amavutils/d' $1
sed -i '/MediaPlayer/d' $1
sed -i '/VideoActivity/d' $1
sed -i '/NtpService/d' $1
sed -i '/SocketClient/d' $1
sed -i '/PppoeMonitor/d' $1
sed -i '/\/StateMachine/d' $1


