#!/bin/sh

LOGFILE=$1
TAGFILE=$2
PATTERN=""

if [ $# -ne 2 ]
then
echo "$0 [log] [tagfile]"
else
while read line
do
echo $line
PATTERN=$PATTERN"\|"$line
done < $TAGFILE

echo ${PATTERN}

echo ""

#sed -n /$PATTERN/p $LOGFILE 
fi

