#!/bin/sh

usage()
{
        echo "download file by socat" >&2
        echo "usage:`basename $0` [addr] [filepath]" >&2
	 	exit 1
}

if [ $# -lt 2 ];then
        usage
fi


socat -u tcp:$1:9000 open:$2,create
md5sum $2

       
