#!/bin/sh

usage()
{
        echo "Usage: $(basename $0) [commitid] [filepath]" >&2
        exit 1
}


if [ $# -ne 2 ];then
        usage
fi

GITDIFF=$(git diff $FILEPATH)
if [ x${GITDIFF}y != "xy" ]; then
echo "unstaged change!!!"
exit 1
fi

GITDIFF=$(git diff --cached $FILEPATH)
if [ x${GITDIFF}y != "xy" ]; then
echo "uncommitted change!!!"
exit 2
fi

COMMIT_ID=$1
FILEPATH=$2
DIRNAME=$(dirname revision.$COMMIT_ID/$FILEPATH)
BASENAME=$(basename $FILEPATH)

rm -fr ./$DIRNAME

mkdir -p $DIRNAME

git checkout $COMMIT_ID  $FILEPATH
cp $FILEPATH $DIRNAME

git checkout $COMMIT_ID^  $FILEPATH

cp $FILEPATH $DIRNAME/${BASENAME}.prev
git checkout HEAD $FILEPATH



